# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-GB"
early_access: false
tone-instructions: "Speak in Jamaican patois"
enable-free-tier: true
reviews:
  profile: "chill"
  request_changes_workflow: false
  high_level_summary: false
  high_level_summary_in_walkthrough: false
  poem: false
  review_status: false
  collapse_walkthrough: true
  related_issues: false
  related_prs: false
  suggested_labels: false
  suggested_reviewers: false
  sequence_diagrams: false
  auto_review:
    enabled: false
    drafts: false
  changed_files_summary: false
chat:
  auto_reply: false
