[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NPM_FLAGS = "--legacy-peer-deps"
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "https://api.imprint.gg/:splat"
  status = 200
  force = true
  methods = ["POST", "OPTIONS"]
  [redirects.headers]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, token"
    Access-Control-Allow-Methods = "POST, OPTIONS"
