[[redirects]]
  from = "/api/match"
  to = "https://api.imprint.gg/match"
  status = 200
  force = true
  methods = ["POST", "OPTIONS"]
  headers = {
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "Origin, X-Requested-With, Content-Type, Accept, token"
    Access-Control-Allow-Methods = "POST, OPTIONS"
  }